# Site settings
title: Walker IO
email: info@walker.io
description: > # this means to ignore newlines until "baseurl:"
  Input/Output By Nestor Walker
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://walker.io" # the base hostname & protocol for your site
twitter_username: nestorwalker
github_username:  nestorw
permalink: pretty

# Build settings
markdown: kramdown
gems:
   - jekyll-coffeescript
